$answer = Read-Host "Are you sure you want to delete all Azure provisioning information (generated by azd init) from this repo's local workspace? (y/n)"
if ($answer -ne 'y') {
	Write-Host "Aborting uninit process."
	exit
}

Remove-Item .\.azure\ -Recurse -Force | Out-Null
Remove-Item .\azure.yaml -Force | Out-Null
Remove-Item .\next-steps.md -Force | Out-Null

Write-Host "Finished."
